# Generated by Django 3.1.6 on 2021-02-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['post_date'], 'permissions': (('can_edit_blog_post', 'Edit blog post'),)},
        ),
    ]
