# Generated by Django 3.1.6 on 2021-02-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reaction',
            field=models.CharField(default='This is great!', max_length=200),
        ),
    ]
