# Generated by Django 3.1.3 on 2021-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='pseudonym',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
