# Generated by Django 3.1.3 on 2021-02-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogger_pseudonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reaction',
            field=models.TextField(default='This is great!', max_length=500),
        ),
    ]
