# Generated by Django 3.1.3 on 2021-02-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210211_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogger'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reaction',
            field=models.TextField(default='', max_length=500),
        ),
    ]
